name: sample workflow
on:
  push:
    branches:
      - dev1
  workflow_dispatch:

jobs:
  demojob1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: display a message
        run: echo "welcome to GHA!!!"
      - name: display the current directory
        run: 
          pwd
          ls
      - name: install JDK
        uses: actions/setup-java@v4.6.0
        with: 
          distribution: 'temurin'
          java-version: '8'
      - name: execute maven
        run: mvn verify
      - name: display the content after execution
        run: ls
  demojob2:
    runs-on: ubuntu-latest
    needs: [demojob1]
    steps: 
      - name: checkout code
        uses: actions/checkout@v4.2.2
