name: Self hosted runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'sureshdubey/SeleniumJavaAdvanceFramework'
        token: ${{ secret.GH_PAT }}
        path: 'java-framework-repo'
    
    - name: Build with Maven
      run: mvn clean
