name: Self hosted runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: suresh-machine
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Maven
      run: mvn verify
  job2:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'sureshdubey/SeleniumJavaAdvanceFramework'
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
