name: Self hosted runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'sureshdubey/SeleniumJavaAdvanceFramework'
        token: ${{ secrets.GH_PAT }}
        path: 'java-framework-repo'
    - name: install JDK
      uses: actions/setup-java@v4.6.0
      with:
          distribution: 'temurin'
          java-version: '8'
    - name: Build with Maven
      run:
        source ~/.bash_profile
        mvn -version
